// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

var findTheDifference = function (s, t) {
  const hash = {};

  for (let i = 0; i < t.length; i++) {
    if (!hash[t[i]]) {
      hash[t[i]] = 1;
    } else {
      hash[t[i]]++;
      t;
    }
  }

  for (let i = 0; i < s.length; i++) {
    hash[s[i]]--;
  }

  return Object.entries(hash).filter((elem) => elem[1] === 1)[0][0];
};

console.log(findTheDifference('abcd', 'abcde'));
